### ISSUE TITLE
Multiple <section> containers

### ISSUE THREAD

**Issue by rule13** [CodyHouse/cd-sticky-sharebar-changelog#3]
I am working on a page that has multiple <section> containers (for visual layout reasons).  The "sticky share" does not seem to like this structure.  It gets triggered but disappears as you scroll down the page and hit the next <section>.  Is there a way to make this work on pages that have multiple <section> containers?

**Comment by sebastiano-guerriero** [comment]
It sounds like a z-index problem. Have you placed the sharebar at the bottom of your HTML structure (i.e., not inside a .container element)?

**Comment by claudia-romano** [comment]
Hi there, I'm closing this issue as no additional info was provided. Feel free to reopen it if you are still experiencing problems. Cheers!
